import streamlit as st
import yfinance as yf
import pandas as pd
import pandas_ta as ta
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression
from datetime import datetime, timedelta
import requests
from fpdf import FPDF
import base64

# ==========================================
# 1. CONFIG & STYLING
# ==========================================
st.set_page_config(layout="wide", page_title="StockOracle AI", page_icon="🔮")

st.markdown("""
<style>
    .metric-card { background-color: #0e1117; border: 1px solid #262730; border-radius: 10px; padding: 20px; text-align: center; }
    .ad-banner { background-color: #262730; padding: 15px; text-align: center; color: #FFD700; border: 1px dashed #FFD700; margin-bottom: 20px; border-radius: 10px; }
    .report-btn { width: 100%; }
</style>
""", unsafe_allow_html=True)

# ==========================================
# 2. PDF GENERATOR ENGINE
# ==========================================
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 20)
        self.cell(0, 10, 'StockOracle AI - Analyst Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by StockOracle AI', 0, 0, 'C')

def create_pdf_report(ticker, df, fund, verdict, reasons, news):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- TITLE SECTION ---
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, f"Analysis for: {fund['name']} ({ticker})", 0, 1, 'L')
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'L')
    pdf.line(10, 35, 200, 35)
    pdf.ln(10)
    
    # --- VERDICT BADGE ---
    pdf.set_font("Arial", "B", 14)
    pdf.cell(50, 10, "AI Verdict:", 0, 0)
    
    # Color logic isn't supported easily in simple text, so we use text indicators
    pdf.set_font("Arial", "B", 16)
    pdf.set_text_color(0, 128, 0) if "BUY" in verdict else pdf.set_text_color(255, 0, 0)
    pdf.cell(0, 10, verdict, 0, 1)
    pdf.set_text_color(0, 0, 0) # Reset black
    pdf.ln(5)
    
    # --- PRICE DATA ---
    current_price = df['Close'].iloc[-1]
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 10, f"Current Price: {current_price:,.2f} | P/E Ratio: {fund['pe_ratio']}", 0, 1)
    pdf.ln(5)
    
    # --- REASONING ---
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Key Analysis Logic:", 0, 1)
    pdf.set_font("Arial", "", 11)
    for reason in reasons:
        pdf.cell(0, 8, f"- {reason}", 0, 1)
    pdf.ln(10)
    
    # --- FUNDAMENTALS TABLE ---
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Company Fundamentals:", 0, 1)
    pdf.set_font("Arial", "", 11)
    
    metrics = [
        ("Market Cap", f"{fund['market_cap']:,}"),
        ("Sector", fund['sector']),
        ("Beta (Volatility)", f"{fund['beta']}"),
        ("Recommendation", verdict)
    ]
    
    for key, val in metrics:
        pdf.cell(90, 8, key, 1)
        pdf.cell(90, 8, str(val), 1, 1)
    pdf.ln(10)
    
    # --- NEWS SECTION ---
    if news:
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Recent News Headlines:", 0, 1)
        pdf.set_font("Arial", "", 10)
        for n in news[:3]:
            title = n['title'][:80] + "..." if len(n['title']) > 80 else n['title']
            pdf.cell(0, 8, f"* {title}", 0, 1)
            
    return pdf.output(dest="S").encode("latin-1")

# ==========================================
# 3. DATA & AI ENGINE
# ==========================================
@st.cache_data(ttl=3600)
def get_stock_data_cached(ticker):
    try:
        session = requests.Session()
        session.headers.update({"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/91.0.4472.124 Safari/537.36"})
        stock = yf.Ticker(ticker, session=session)
        hist = stock.history(period="1y")
        if hist.empty: return None, None, None
        
        info = stock.info
        fundamentals = {
            "pe_ratio": info.get('forwardPE', info.get('trailingPE', 0)),
            "market_cap": info.get('marketCap', 0),
            "sector": info.get('sector', 'Unknown'),
            "beta": info.get('beta', 0),
            "name": info.get('longName', ticker)
        }
        return hist, fundamentals, stock.news
    except: return None, None, None

def analyze_stock(df):
    df['EMA_200'] = ta.ema(df['Close'], length=200)
    df['RSI'] = ta.rsi(df['Close'], length=14)
    last = df.iloc[-1]
    score = 0
    reasons = []
    
    if last['Close'] > last['EMA_200']: score += 2; reasons.append("Price > 200 EMA (Bullish Trend)")
    else: score -= 2; reasons.append("Price < 200 EMA (Bearish Trend)")
        
    if last['RSI'] < 30: score += 1; reasons.append("RSI Oversold (Potential Bounce)")
    elif last['RSI'] > 70: score -= 1; reasons.append("RSI Overbought (Potential Pullback)")
    
    if score >= 2: verdict = "STRONG BUY"
    elif score >= 1: verdict = "BUY"
    elif score <= -2: verdict = "SELL"
    else: verdict = "HOLD"
    return verdict, score, reasons, df

def run_prediction(df):
    df = df.reset_index()
    df['Ord'] = df['Date'].map(pd.Timestamp.toordinal)
    model = LinearRegression().fit(df[['Ord']].values, df['Close'].values)
    future_dates = [df['Date'].iloc[-1] + timedelta(days=i) for i in range(1, 31)]
    future_pred = model.predict(np.array([d.toordinal() for d in future_dates]).reshape(-1, 1))
    return future_dates, future_pred

# ==========================================
# 4. MAIN UI
# ==========================================
st.sidebar.title("💎 StockOracle Pro")
st.sidebar.markdown("---")
st.sidebar.info("💡 **Tip:** Download the PDF report to share with clients or save for your records.")
st.sidebar.markdown("---")
st.sidebar.write("☕ **Support the Dev**")
st.sidebar.markdown("[![Buy Me A Coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://www.buymeacoffee.com)")

st.title("🔮 StockOracle: AI Market Analyst")

# SPONSORED BANNER (MONETIZATION)
st.markdown('<div class="ad-banner">📢 <b>Start Investing Today!</b> Open a Free Demat Account with [Your Affiliate Link] & Get ₹0 Brokerage for 30 Days.</div>', unsafe_allow_html=True)

ticker = st.text_input("Enter Symbol (e.g., RELIANCE.NS, BTC-USD):", "RELIANCE.NS").upper()

if st.button("🚀 Analyze Stock"):
    with st.spinner("Analyzing Market Data..."):
        hist, fund, news = get_stock_data_cached(ticker)
        
        if hist is not None:
            verdict, score, reasons, df_an = analyze_stock(hist)
            f_date, f_price = run_prediction(hist)
            
            # --- DASHBOARD ---
            c1, c2, c3 = st.columns(3)
            c1.metric("Stock", fund['name'])
            c2.metric("Price", f"{df_an['Close'].iloc[-1]:,.2f}")
            color = "green" if "BUY" in verdict else "red" if "SELL" in verdict else "gray"
            c3.markdown(f"## :{color}[{verdict}]")
            
            # --- PLOT ---
            st.subheader(f"📈 {ticker} Trend & Prediction")
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=hist.index, y=hist['Close'], name='History', line=dict(color='blue')))
            fig.add_trace(go.Scatter(x=f_date, y=f_price, name='AI Forecast', line=dict(color='orange', dash='dash')))
            st.plotly_chart(fig, use_container_width=True)
            
            # --- REPORT GENERATION ---
            st.subheader("📝 Professional Report")
            c_gen, c_view = st.columns([1, 2])
            
            with c_gen:
                st.write("Generate a detailed PDF report for this stock.")
                pdf_bytes = create_pdf_report(ticker, hist, fund, verdict, reasons, news)
                st.download_button(
                    label="📄 Download PDF Report",
                    data=pdf_bytes,
                    file_name=f"{ticker}_AI_Report.pdf",
                    mime="application/pdf",
                )
            
            with c_view:
                st.info("The PDF includes: \n- AI Verdict & Reasoning \n- Fundamental Metrics (P/E, Market Cap) \n- Recent News Headlines")

        else:
            st.error("Could not fetch data. Try a different ticker.")